### ISSUE TITLE
✅ Success notification

### ISSUE THREAD

**Issue by tristanMatthias** [MikeKovarik/rollup-plugin-notify#1]
Love this plugin! Was wondering if you'd possibly consider extending it to include a successful build notification too?

**Comment by MikeKovarik** [comment]
Glad you like it. I thought success notification would be rather annoying. But if you'd find it useful in your workflow then why not.

I made a quick commit, it was written off the top of my head. It's nothing fancy and doesn't tell name of the file(s) or anything, just that it finished without problems. I haven't published it yet because I didn't even test it myself bit it should work. Though i'd feel safer if you could take a look at it, give it a spin and tell me how it works. Or maybe even improve it.

**Comment by tristanMatthias** [comment]
Ok thanks! I spotted an error and merged a pull request. It also has some more improved icons
https://github.com/MikeKovarik/rollup-plugin-notify/pull/3

**Comment by MikeKovarik** [comment]
done. 1.0.4 released

**Comment by tristanMatthias** [comment]
Thanks @MikeKovarik!
